### PR TITLE
COE-417: filter for fragmentType instead of type

### PR DESCRIPTION
**Pull request by mvoigt-sag**

### CODE REVIEW

**Comment by mvoigt-sag** [comment]
@dirk-peter-sag I updated the PR; now it is working properly in my test environment

**Review by haraldmeyer — APPROVED** [review]
Looks ok to me, but best if Dirk also approves.

**Comment by mvoigt-sag** [comment]
> @dirk-peter-sag I updated the PR; now it is working properly in my test environment

@dirk-peter-sag any chance you could have a look at this during the next few days? We're currently starting the process to release Fix1 of OEE app...

**Comment by dirk-peter-c8y** [comment]
sorry, mention went under the radar, due to a flood of notifications in another project. 
@mvoigt-sag I will see to check in the next days.

**Review by dirk-peter-c8y — APPROVED** [review]
all fine and working fine for me as well

**Pull request merged**
